### PR TITLE
Feat/add register async

### PR DESCRIPTION
**Pull request by kleberoliveira**

### CODE REVIEW

**Comment by kleberoliveira** [comment]
Hi @lehh, I've created new approaches for async methods to inject other modules when importing the SoapModule. Also, I've put the Auth basic as an option to start the soap client already authenticated.

It's hard for me to create the unit test, but I got 90% of coverage, I think that's enough :)

**Comment by lehh** [comment]
Hello @kleberoliveira, thanks a lot for the pull request. Could you please update the README with the new features too? After that I will merge the pull request and publish the package.

**Comment by kleberoliveira** [comment]
@lehh done :)

**Comment by lehh** [comment]
Package published on npm. Thanks again!

**Pull request merged**
